import dynamics_complex_polynomials_rational_maps_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace dynamics_complex_polynomials_rational_maps_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end dynamics_complex_polynomials_rational_maps_theorem_canonical_lane_mathlib
end HautevilleHouse
